"""
deliver_workflow.py

Sends the completed workflow to the user via Gmail (using the Gmail MCP tool
available to Claude Code). This script is NOT called directly — it outputs
a structured payload that the Claude agent reads to compose and send the email.

Usage (called by Claude agent, not directly):
    python tools/deliver_workflow.py

Output:
    Prints a JSON delivery payload to stdout for the agent to act on.
    {
      "to": "...",
      "subject": "...",
      "body": "...",
      "board_url": "...",
      "png_path": "...",       # null if export unavailable
      "png_available": true|false
    }

The Claude agent will use this payload with the Gmail MCP tool to:
    1. Compose the email with the board link
    2. Attach the PNG if available
    3. Send it to DELIVERY_EMAIL
"""

import json
import os
from pathlib import Path

from dotenv import load_dotenv

load_dotenv()


def main():
    export_info = json.loads(Path(".tmp/export_info.json").read_text())
    workflow = json.loads(Path(".tmp/workflow.json").read_text())

    title = workflow.get("title", "Workflow Diagram")
    node_count = len(workflow.get("nodes", []))
    edge_count = len(workflow.get("edges", []))
    board_url = export_info["board_url"]
    png_path = export_info.get("png_path")
    png_available = export_info.get("export_available", False)

    body = f"""Hi,

Your workflow diagram "{title}" is ready.

Summary:
- {node_count} steps/nodes
- {edge_count} connections

View and edit the live Miro board here:
{board_url}

{"The PNG export is attached to this email." if png_available else "PNG export requires a Miro paid plan. You can export manually: open the board → Export → Export to PNG."}

Workflow generated by the WAT Workflow Agent.
"""

    payload = {
        "to": os.environ.get("DELIVERY_EMAIL", ""),
        "subject": f"Workflow Ready: {title}",
        "body": body,
        "board_url": board_url,
        "png_path": png_path,
        "png_available": png_available,
    }

    output_path = Path(".tmp/deliver_payload.json")
    output_path.write_text(json.dumps(payload, indent=2))
    print(json.dumps(payload, indent=2))
    return payload


if __name__ == "__main__":
    main()
